### ISSUE TITLE
`lightyear_replication` build fails

### ISSUE THREAD

**Issue by esuriru** [cBournhonesque/lightyear#1142]
Attempted to build `simple_box`  with rust 1.87; on windows 11 platform, results in 2 errors

Log output:
```
   Compiling lightyear_connection v0.22.5 (D:\lightyear\lightyear_connection)                                                                   
   Compiling lightyear_transport v0.22.5 (D:\lightyear\lightyear_transport)                                                                     
   Compiling xwt-wtransport v0.13.2                                                                                                             
   Compiling bevy_gizmos_macros v0.16.1                                                                                                         
   Compiling bevy_input_focus v0.16.1                                                                                                           
   Compiling bevy_image v0.16.1                                                                                                                 
   Compiling lightyear_messages v0.22.5 (D:\lightyear\lightyear_messages)
   Compiling bevy_winit v0.16.1                                                                                                                 
   Compiling aeronet_webtransport v0.14.0                                                                                                       
   Compiling lightyear_aeronet v0.22.5 (D:\lightyear\lightyear_aeronet)
   Compiling bevy_mesh v0.16.1                                                                                                                  
   Compiling lightyear_sync v0.22.5 (D:\lightyear\lightyear_sync)                                                                               
   Compiling lightyear_replication v0.22.5 (D:\lightyear\lightyear_replication)                                                                 
   Compiling egui v0.31.1                                                                                                                       
error[E0658]: `let` expressions in this position are unstable                                                                                   
   --> lightyear_replication\src\send\buffer_bis.rs:340:33
    |
340 |         if delta_compression && let Some((delta_manager, shared_tick)) = delta {
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable                                                                                   
   --> lightyear_replication\src\send\buffer_bis.rs:533:41
    |
533 |                 if delta_compression && let Some(delta) = delta {
    |                                         ^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

   Compiling webbrowser v1.0.5                                                                                                                  
   Compiling lightyear_netcode v0.22.5 (D:\lightyear\lightyear_netcode)                                                                         
   Compiling lightyear_udp v0.22.5 (D:\lightyear\lightyear_udp)                                                                                 
   Compiling bevy-inspector-egui-derive v0.32.0                                                                                                 
For more information about this error, try `rustc --explain E0658`.                                                                             
error: could not compile `lightyear_replication` (lib) due to 2 previous errors  
```

**Comment by esuriru** [comment]
Looks like this should work in Rust 1.88 edition 2024 as mentioned in https://github.com/rust-lang/rust/issues/53667. Close this issue if this is of intention to stay with this syntax.
